apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-org3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api-org3
  template:
    metadata:
      labels:
        name: api-org3
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc
        - name: ca-client-config
          configMap:
            name: ca-client-config
            items:
              - key: config.json
                path: config.json
                mode: 0544
      containers:
        - name: api-org3
          stdin: true
          tty: true
          resources:
            limits:
              memory: "450Mi"
              cpu: "400m"
            requests:
              memory: "400Mi"
              cpu: "150m"
          image:  piyushap18/dsg-sdk-org3:3
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /usr/src/app/connection-profile
              subPath: connection-profile
            - name: data
              mountPath: /organizations
              subPath: organizations
            - name: data
              mountPath: /usr/src/app/wallet-org3
              subPath: wallet-org3
            - mountPath: /usr/src/app/config.json
              name: ca-client-config
              subPath: config.json  
---
apiVersion: v1
kind: Service
metadata:
  name: api-load-org3
spec:
  selector:
    name: api-org3
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-org3
  name: api-org3
spec:
  type: ClusterIP
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    name: api-org3